### ISSUE TITLE
Web server does not drop cached copy

### ISSUE THREAD

**Issue by rreas** [q-centrix/rugular#46]
Leaving a note about this. The server does not always resend the latest file from disk when it changes. Running, for example, `python -m SimpleHTTPServer 8000` works as expected whereas the built-in node server still serves the old file content.

**Comment by shicholas** [comment]
Cool sounds good. I think nginx is ideally the best option for serving a rugular app. So I'll make sure to add that soon.

**Comment by rreas** [comment]
Your current solution seems fine to me. NGINX sounds like overkill for local dev. possibly. I just think the caching issue needs to be fixed. Is there a configuration flag for the node server to just always serve from disk?

**Comment by rreas** [comment]
I like NGINX locally if you want to test everything including a running API.

**Comment by rreas** [comment]
Seems to be working fine now with `rugular tmux`
