### ISSUE TITLE
Guard running at 100% CPU

### ISSUE THREAD

**Issue by rreas** [q-centrix/rugular#53]
Replaced Guardfile with this seems to help

```ruby
require "#{__dir__}/guards/rugular.rb"

guard :rugular do
  watch /^src\/.+\.(coffee|haml|png|jpg|ttf|woff)$/
  watch 'bower_components.yaml'

  ignore %r(^bower_components/*)
  ignore %r(^node_modules/*)
  ignore %r(^release/*)
  ignore %r(^dist/*)
  ignore %r(^vendor/*)
  ignore %r(^\.tmp/*)
end
```

**Comment by shicholas** [comment]
ha is it that hard to ask for a PR? jk, I'll add this now.

**Comment by rreas** [comment]
no wait

**Comment by rreas** [comment]
I'm not ready to make a PR yet, that's why. I'm still testing and adding things.

**Comment by shicholas** [comment]
fwiw, i previously used the ``directory`` option in guard, but decided not to use it once I felt ``bower_components.yml`` belonged outside the ``src`` folder.

**Comment by rreas** [comment]
Setup seems fine. According to rb-fsevent bug reports it seems inevitable to need to use ignores.
