### ISSUE TITLE
Protractor requirements not installed

### ISSUE THREAD

**Issue by rreas** [q-centrix/rugular#57]
Not entirely sure about this. It seems like you need to do the following:

``` sh
./node_modules/protractor/bin/webdriver-manager update
```

Should protractor run like karma?

**Comment by shicholas** [comment]
AFAIK, selenium should always be running but protractor shouldn't; protractor tests are intended to be run a few times while developing and once in CI.

**Comment by rreas** [comment]
I figured you'd say that. Still, the deps need to be installed :)

**Comment by ghost** [comment]
🤦‍♂ hope you're doing well @rreas!

**Comment by rreas** [comment]
Same :)
